[package]

name = "cql"
version = "0.0.2"
authors = ["Ignacio Martín <natx.mc@gmail.com>"]

[dependencies]
num = "0.1.28"
uuid = "0.1.18"
eventual = "0.1.4"
mio = "0.5.0"
bytes = "0.3.0"
slab = "0.1.2"
byteorder = "0.4.2"
enum_primitive = "0.1.0"
time = "0.1.34"
decimal = "0.4.0"